const tradutorCriarUsu = {
    pt: {
        page: "Página",
        pageTitle: "Criar Usuário",
        nomeTitle: "Nome",
        nomePlaceholder: "Escreva o nome",
        emailTitle: "E-mail",
        emailPlaceholder: "Escreva o e-mail",
        selectTitleGender: "Selecione um gênero",
        selectTitleOp: "Selecione uma opção:",
        selectTitleGenderOp2: "Masculino",
        selectTitleGenderOp3: "Feminino",
        selectTitleRole: "Selecione uma função",
        selectTitleRoleOp2: "Diretor",
        selectTitleRoleOp3: "Administrador",
        selectTitleRoleOp4: "Solicitante",
        senhaTitulo: "Senha",
        senhaPlaceholder: "*******",
        buttonCriar: "Criar",
        errorTitle: "Falha ao criar novo usuário",
        errorNameVazio: "Por favor escreva um nome",
        errorNameTamanho: "O tamanho do nome é muito grande",
        errorEmailVazio: "Por favor escreva um e-mail",
        errorValidarEmail: "O e-mail deve ter @ e .com",
        errorTamanhoEmail: "O tamanho do e-mail é muito grande",
        errorSelectDefaultGender: "Selecione um gênero",
        errorSenhaVazia: "Por favor escreva uma senha",
        errorTamanoSenha: "A senha deve ter entre 8 e 15 caracteres",
        errorSelectDefaultRole: "Selecione uma função",
        messageSucssefuly: "Usuário criado com sucesso",

        
    },
    en: {
        page: "Page",
        pageTitle: "Create User",
        nomeTitle: "Name",
        nomePlaceholder: "Write a name",
        emailTitle: "E-mail",
        emailPlaceholder: "Write a e-mail",
        selectTitleGender: "Select a gender",
        selectTitleOp: "Select a option:",
        selectTitleGenderOp2: "Masculine",
        selectTitleGenderOp3: "Feminine",
        selectTitleRole: "Select a role",
        selectTitleRoleOp2: "Director",
        selectTitleRoleOp3: "Administrator",
        selectTitleRoleOp4: "Requester",
        senhaTitulo: "Password",
        senhaPlaceholder: "*******",
        buttonCriar: "Create",
        errorTitle: "Failed to create new user",
        errorNameVazio: "Please write a name",
        errorNameTamanho: "Name size is too big",
        errorEmailVazio: "Please write a e-mail",
        errorValidarEmail: "E-mail must have @ and .com",
        errorTamanhoEmail: "E-mail size is too big",
        errorSelectDefaultGender: "Select a gender",
        errorSenhaVazia: "Please write a password",
        errorTamanoSenha: "Password must be between 8 and 15 characters long",
        errorSelectDefaultRole: "Select a role",
        messageSucssefuly: "User created succssefully",

    }
};


export default tradutorCriarUsu;
