const tradutorUpdateProfile = {
    pt: {
        page: "Página",
        pageTitle: "Alterar perfil",
        nomeTitle: "Nome",
        nomePlaceholder: "Escreva o nome",
        emailTitle: "E-mail",
        emailPlaceholder: "Escreva o e-mail",
        selectTitleGender: "Selecione um gênero",
        selectTitleOp: "Selecione uma opção:",
        selectTitleGenderOp2: "Masculino",
        selectTitleGenderOp3: "Feminino",
        alterarSenhaTitle: "Alterar senha",
        senhaAntiga: "Senha Antiga",
        senhaNova: "Senha Nova",
        senhaPlaceholder: "*******",
        buttonAtualizar: "atualizar",
        errorTitle: "Falha ao atualizar o usuário",
        errorNameVazio: "Por favor escreva um nome",
        errorNameTamanho: "O tamanho do nome é muito grande",
        errorEmailVazio: "Por favor escreva um e-mail",
        errorValidarEmail: "O e-mail deve ter @ e .com",
        errorTamanhoEmail: "O tamanho do e-mail é muito grande",
        errorSelectDefaultGender: "Selecione um gênero",
        errorSenhaVaziaVelha: "Por favor escreva a senha antiga",
        errorSenhaNova: "Por favor escreva a nova senha",
        errorTamanoSenha: "A senha deve ter entre 8 e 15 caracteres",
        errorSenhasIguais: "A nova senha não pode ser igual à senha antiga",
        messageSucssefuly: "Usuário atualizado com sucesso",

        
    },
    en: {
        page: "Page",
        pageTitle: "Update profile",
        nomeTitle: "Name",
        nomePlaceholder: "Write a name",
        emailTitle: "E-mail",
        emailPlaceholder: "Write a e-mail",
        selectTitleGender: "Select a gender",
        selectTitleOp: "Select a option:",
        selectTitleGenderOp2: "Masculine",
        selectTitleGenderOp3: "Feminine",
        alterarSenhaTitle: "Change password",
        senhaAntiga: "Old password",
        senhaNova: "New password",
        senhaPlaceholder: "*******",
        buttonAtualizar: "Update",
        errorTitle: "Failed to update user",
        errorNameVazio: "Please write a name",
        errorNameTamanho: "Name size is too big",
        errorEmailVazio: "Please write a e-mail",
        errorValidarEmail: "E-mail must have @ and .com",
        errorTamanhoEmail: "E-mail size is too big",
        errorSelectDefaultGender: "Select a gender",
        errorSenhaVaziaVelha: "Please write the old password",
        errorSenhaNova: "Please write the new password",
        errorTamanoSenha: "Password must be between 8 and 15 characters long",
        errorSenhasIguais: "The new password cannot be the same as the old password.",
        messageSucssefuly: "User updated succssesfully",

    }
};


export default tradutorUpdateProfile;
