const tradutorCriarUsu = {
    pt: {
        page: "Página",
        pageTitle: "Criar Usuário",
        nomeTitle: "Nome",
        nomePlaceholder: "Escreva o nome",
        emailTitle: "E-mail",
        emailPlaceholder: "Escreva o e-mail",
        selectTitleGender: "Selecione um gênero",
        selectTitleGenderOp1: "Selecione uma opção",
        selectTitleGenderOp2: "Masculino",
        selectTitleGenderOp3: "Feminino",
        selectTitleRole: "Selecione uma função",
        selectTitleRoleOp1: "Selecione uma opção",
        selectTitleRoleOp2: "Diretor",
        selectTitleRoleOp3: "Administrador",
        selectTitleRoleOp4: "Solicitante",
        senhaTitulo: "Senha",
        senhaPlaceholder: "Escreva a senha",
        buttonCriar: "Criar",
        errorTitle: "Falha ao criar novo usuário",
        errorNameVazio: "Por favor escreva um nome",
        errorNameTamanho: "O tamanho do nome é muito grande",
        errorEmailVazio: "Por favor escreva um e-mail",
        errorValidarEmail: "O e-mail deve ter @ e .com",
        errorTamanhoEmail: "O tamanho do e-mail é muito grande",
        errorSelectDefaultGender: "Selecione um gênero",
        errorSenhaVazia: "Por favor escreva uma senha",
        errorTamanoSenha: "A senha deve ter entre 8 e 15 caracteres",
        errorSelectDefaultRole: "Selecione uma função",
        messageSucssefuly: "Usuário criado com sucesso",

        
    },
    en: {
        page: "Page",
        pageTitle: "Create User",
        nomeTitle: "",
        nomePlaceholder: "",
        emailTitle: "",
        emailPlaceholder: "",
        selectTitleGender: "",
        selectTitleGenderOp1: "",
        selectTitleGenderOp2: "",
        selectTitleGenderOp3: "",
        selectTitleRole: "",
        selectTitleRoleOp1: "",
        selectTitleRoleOp2: "",
        selectTitleRoleOp3: "",
        selectTitleRoleOp4: "",
        senhaTitulo: "",
        senhaPlaceholder: "",
        buttonCriar: "",
        errorTitle: "",
        errorNameVazio: "",
        errorNameTamanho: "",
        errorEmailVazio: "",
        errorValidarEmail: "",
        errorTamanhoEmail: "",
        errorSelectDefaultGender: "",
        errorSenhaVazia: "",
        errorTamanoSenha: "",
        errorSelectDefaultRole: "",
        messageSucssefuly: "",

    }
};


export default tradutorCriarUsu;
