const tradutorUpdateUser = {
    pt: {
        page: "Página",
        pageTitle: "Alterar usuário",
        nomeTitle: "Nome",
        nomePlaceholder: "Escreva o nome",
        emailTitle: "E-mail",
        emailPlaceholder: "Escreva o e-mail",
        selectTitleGender: "Selecione um gênero",
        selectTitleOp: "Selecione uma opção:",
        selectTitleGenderOp2: "Masculino",
        selectTitleGenderOp3: "Feminino",
        selectTitleRole: "Selecione uma função",
        selectTitleRoleOp2: "Diretor",
        selectTitleRoleOp3: "Administrador",
        selectTitleRoleOp4: "Solicitante",
        buttonAtualizar: "atualizar",
        errorTitle: "Falha ao atualizar o usuário",
        errorNameVazio: "Por favor escreva um nome",
        errorNameTamanho: "O tamanho do nome é muito grande",
        errorEmailVazio: "Por favor escreva um e-mail",
        errorValidarEmail: "O e-mail deve ter @ e .com",
        errorTamanhoEmail: "O tamanho do e-mail é muito grande",
        errorSelectDefaultRole: "Selecione uma função",
        errorSelectDefaultGender: "Selecione um gênero",
        messageSucssefuly: "Usuário atualizado com sucesso",

        
    },
    en: {
        page: "Page",
        pageTitle: "Update user",
        nomeTitle: "Name",
        nomePlaceholder: "Write a name",
        emailTitle: "E-mail",
        emailPlaceholder: "Write a e-mail",
        selectTitleGender: "Select a gender",
        selectTitleOp: "Select a option:",
        selectTitleGenderOp2: "Masculine",
        selectTitleGenderOp3: "Feminine",
        selectTitleRole: "Select a role",
        selectTitleRoleOp2: "Director",
        selectTitleRoleOp3: "Administrator",
        selectTitleRoleOp4: "Requester",
        buttonAtualizar: "Update",
        errorTitle: "Failed to update user",
        errorNameVazio: "Please write a name",
        errorNameTamanho: "Name size is too big",
        errorEmailVazio: "Please write a e-mail",
        errorValidarEmail: "E-mail must have @ and .com",
        errorTamanhoEmail: "E-mail size is too big",
        errorSelectDefaultRole: "Select a role",
        errorSelectDefaultGender: "Select a gender",
        messageSucssefuly: "User updated sucssefuly",

    }
};


export default tradutorUpdateUser;
